[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
ffi = false
fs_permissions = []

[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 64
depth = 64
fail_on_revert = true
